#!/usr/bin/env Rscript

# Shiny Server starts each R worker with a deliberately small environment.
# Persist only the reviewed settings below into the non-root user's R startup
# profile. Shiny Server intentionally gives workers only HOME/LANG/PATH, then R
# reads this file during normal startup. Provider credentials are excluded; the
# worker receives only the path to a mounted secret file.
allowlist <- c(
  "R_LIBS_USER",
  "RENV_PATHS_LIBRARY",
  "RENV_PATHS_CACHE",
  "RENV_CONFIG_AUTO_SNAPSHOT",
  "RENV_CONFIG_SANDBOX_ENABLED",
  "ENA3D_PROJECT_ROOT",
  "ENA3D_BUILD_ID",
  "ENA3D_GIT_COMMIT",
  "ENA3D_APP_VERSION",
  "ENA3D_RUNTIME_PROFILE",
  "ENA3D_ANALYTICS_PROVIDER",
  "ENA3D_AI_ENABLED",
  "ENA3D_MAX_REQUEST_BYTES",
  "ENA3D_MAX_EXCHANGE_FILE_BYTES",
  "ENA3D_MAX_RAW_FILE_BYTES",
  "ENA3D_MAX_RAW_ARCHIVE_BYTES",
  "ENA3D_MAX_RAW_ROWS",
  "ENA3D_MAX_RAW_COLUMNS",
  "ENA3D_MAX_RAW_CELLS",
  "ENA3D_MAX_TRUSTED_FILE_BYTES",
  "ENA3D_MAX_LOADED_BYTES",
  "ENA3D_MAX_SAVED_OBJECTS",
  "ENA3D_MAX_POINT_ROWS",
  "ENA3D_MAX_NODES",
  "ENA3D_MAX_DIMENSIONS",
  "ENA3D_MAX_METADATA_COLUMNS",
  "ENA3D_MAX_TABLE_CELLS",
  "ENA3D_MAX_GROUP_LEVELS",
  "ENA3D_MAX_UNITS",
  "ENA3D_MAX_BOOTSTRAP_SECONDS",
  "ENA3D_MAX_BOOTSTRAP_PROCESSES",
  "ENA3D_QWEN_REGION",
  "ENA3D_QWEN_BASE_URL",
  "ENA3D_QWEN_MODEL",
  "ENA3D_QWEN_TIMEOUT_SECONDS",
  "ENA3D_QWEN_CONNECT_TIMEOUT_SECONDS",
  "ENA3D_QWEN_MAX_REQUEST_BYTES",
  "ENA3D_QWEN_MAX_RESPONSE_BYTES",
  "ENA3D_QWEN_MAX_CONTEXT_BYTES",
  "ENA3D_QWEN_MAX_COMPLETION_TOKENS",
  "ENA3D_QWEN_THINKING_BUDGET",
  "ENA3D_QWEN_TEMPERATURE",
  "ENA3D_AI_MIN_CELL_N",
  "ENA3D_AI_TOP_N",
  "ENA3D_AI_CONTEXT_MAX_CHARS",
  "ENA3D_AI_MAX_CONCURRENT_JOBS",
  "ENA3D_AI_MAX_REQUESTS_PER_HOUR",
  "ENA3D_AI_MAX_EVIDENCE_BYTES",
  "DASHSCOPE_API_KEY_FILE"
)

if ("DASHSCOPE_API_KEY" %in% allowlist) {
  stop("The raw provider key must never enter the worker environment.")
}

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1L || !nzchar(args[[1L]])) {
  stop("Usage: write-runtime-env.R /absolute/path/to/.Rprofile")
}

target <- args[[1L]]
if (!grepl("^/", target)) {
  stop("The runtime environment target must be an absolute path.")
}
target_dir <- dirname(target)
if (!dir.exists(target_dir)) {
  stop("The runtime environment target directory does not exist.")
}

values <- Sys.getenv(allowlist, unset = NA_character_)
values <- values[!is.na(values)]
if (length(values) > 0L) {
  has_line_break <- grepl("[\r\n]", values, perl = TRUE)
  if (any(has_line_break)) {
    stop(
      "Refusing a line break in: ",
      paste(names(values)[has_line_break], collapse = ", ")
    )
  }
}

serialized <- capture.output(dput(as.list(values)))
lines <- c(
  "# Generated by 3D ENA's reviewed container entrypoint.",
  "local({",
  "  ena3d_runtime_env <-",
  paste0("    ", serialized),
  "  if (length(ena3d_runtime_env) > 0L) {",
  "    do.call(Sys.setenv, ena3d_runtime_env)",
  "  }",
  '  ena3d_library <- ena3d_runtime_env[["R_LIBS_USER"]]',
  "  if (!is.null(ena3d_library) && nzchar(ena3d_library)) {",
  "    if (!dir.exists(ena3d_library)) {",
  '      stop("The configured R_LIBS_USER directory does not exist.")',
  "    }",
  "    ena3d_library <- normalizePath(ena3d_library, mustWork = TRUE)",
  "    .libPaths(unique(c(ena3d_library, .libPaths())))",
  "  }",
  "})"
)

temporary <- paste0(target, ".tmp-", Sys.getpid())
on.exit(unlink(temporary, force = TRUE), add = TRUE)
writeLines(lines, con = temporary, useBytes = TRUE)
Sys.chmod(temporary, mode = "0600")
if (!file.rename(temporary, target)) {
  stop("Could not atomically install the runtime environment file.")
}
Sys.chmod(target, mode = "0600")
